CREATE TABLE IF NOT EXISTS market_events (
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category_slug TEXT NOT NULL,
    subcategory_slug TEXT,
    tag_slugs TEXT[] NOT NULL DEFAULT '{}',
    image_url TEXT,
    summary_text TEXT,
    rules_text TEXT NOT NULL,
    context_text TEXT,
    additional_context TEXT,
    resolution_sources TEXT[] NOT NULL DEFAULT '{}',
    resolution_timezone TEXT NOT NULL,
    starts_at TIMESTAMPTZ,
    sort_at TIMESTAMPTZ,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    breaking BOOLEAN NOT NULL DEFAULT FALSE,
    searchable BOOLEAN NOT NULL DEFAULT TRUE,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    hide_resolved_by_default BOOLEAN NOT NULL DEFAULT FALSE,
    group_key TEXT NOT NULL,
    series_key TEXT NOT NULL,
    event_id TEXT NOT NULL UNIQUE,
    group_id TEXT NOT NULL,
    series_id TEXT NOT NULL,
    neg_risk BOOLEAN NOT NULL DEFAULT FALSE,
    oracle_address TEXT NOT NULL,
    publication_status TEXT NOT NULL,
    published_tx_hash TEXT,
    created_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT market_events_publication_status_check CHECK (publication_status IN ('draft'))
);

CREATE TABLE IF NOT EXISTS markets (
    id UUID PRIMARY KEY,
    event_db_id UUID NOT NULL REFERENCES market_events(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    question TEXT NOT NULL,
    question_id TEXT NOT NULL UNIQUE,
    condition_id TEXT UNIQUE,
    market_type TEXT NOT NULL,
    outcome_count INTEGER NOT NULL,
    outcomes TEXT[] NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    sort_order INTEGER NOT NULL,
    publication_status TEXT NOT NULL,
    metadata_hash TEXT,
    oracle_address TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT markets_publication_status_check CHECK (publication_status IN ('draft')),
    CONSTRAINT markets_market_type_check CHECK (market_type IN ('binary')),
    CONSTRAINT markets_outcome_count_check CHECK (outcome_count = 2),
    CONSTRAINT markets_outcomes_length_check CHECK (array_length(outcomes, 1) = 2)
);

CREATE INDEX IF NOT EXISTS markets_event_db_id_sort_order_idx
ON markets (event_db_id, sort_order);
